"""TICKET-H1 (GH-353): end-to-end table judge ladder + committed fixture.

The final ticket of the table-judge-ladder initiative. Everything upstream
(A0-A4, B0-B2, C1-C3, D1a-D1b, E1) is unit/gate-level; this file is the one
place that drives the REAL ``UnifiedPipeline.process()`` on a REAL,
COMMITTED, two-page PDF (``tests/fixtures/table_ladder/``, generated by
``generate_fixture.py`` -- see that module's own docstring and
``tests/fixtures/table_repair/generate_fixture.py``'s precedent) and walks
every terminal the ladder can reach through all four no-silent-loss
surfaces: page disposition, document status, ``metadata.json`` note, and the
CLI summary line (``result.error`` as printed by ``_print_summary``).

The fixture's page 2 reproduces the GH-273 shape: a row-label rotation that
keeps every value in the table (an identical multiset) but binds each value
to the WRONG row label -- the defect two frontier judges both missed
(``docs/log/2026-08-30_table-judge-ladder.md``). Page 1 is a clean,
unambiguous control table with no such shape.

Three terminal scenarios, each contrasting a demoted page against an
ACCEPTED page in the SAME document (proving the demotion is per-page, not a
silent document-wide sweep):

- REJECTED: the (real, injected) judge itself answers FAIL on the shifted
  table -- a content verdict, not retryable.
- Plain UNVERIFIED: an infra (¬S1) rung on the CLEAN table -- nobody could
  look, no mechanical evidence involved at all.
- CLAMPED-UNVERIFIED (E1's flag in STATUS.md): the mechanical binding check
  finds a genuine contradiction on the shifted table AND the real judge
  answers a high-confidence PASS -- CONSILIUM's clamp caps that at
  UNVERIFIED rather than letting the judge's PASS silently erase the
  mechanical evidence (the exact GH-273 failure). Distinguished from plain
  UNVERIFIED by its own audit-event wording ("mechanical binding check found
  a contradiction").

Hermetic throughout, matching every prior GH-353 ticket's own contract: CI
has no ollama and no ``gemini`` binary, so every rung is an injected fake
that decides its verdict from the candidate markdown text it is handed (no
queue-exhaustion risk across the two witnessed tables in one document, since
``_build_table_judge_rungs()`` is called ONCE per document and its rungs are
reused for every page/table -- see ``orchestrator.py:3207``).
``_available_engines_for_agentic`` and ``_resolve_judge_model`` are patched
so the OCR provider ladder and judge-model resolution never touch a live
daemon. Per the #253/#257 trap, every scenario runs flag-off THEN flag-on in
one test and asserts the DELTA the flag makes -- never an absolute outcome
tuple pinned from one machine.

Resume interaction (REJECTED skips on resume, UNVERIFIED reprocesses) is
already covered exhaustively at the production seam
(``_load_terminal_page``) by ``tests/test_ladder_resume.py`` (TICKET-D1b);
repeating it here at the full-``process()`` level would only re-exercise
that same seam through more machinery for no new coverage, so it is
intentionally left to D1b.
"""

from __future__ import annotations

import contextlib
import json
import shutil
from pathlib import Path
from unittest.mock import patch

import pytest

from socr.core.config import EngineType, PipelineConfig
from socr.core.providers import PROFILE_QWEN_LOCAL
from socr.core.result import DocumentStatus, FailureMode, PageOutput, PageStatus
from socr.judge.table_verdict import (
    TABLE_LADDER_UNVERIFIED_KIND,
    Finding,
    FindingCode,
    RungResult,
    TableJudgeVerdict,
)
from socr.pipeline.orchestrator import UnifiedPipeline

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "table_ladder"
FIXTURE_PDF = FIXTURE_DIR / "binding_shift_doc.pdf"
GROUND_TRUTH = FIXTURE_DIR / "ground_truth.json"

fitz = pytest.importorskip("fitz", reason="PyMuPDF not installed")


def _load_gt() -> dict:
    return json.loads(GROUND_TRUTH.read_text())


def _region(gt: dict, region_id: str) -> dict:
    for r in gt["regions"]:
        if r["id"] == region_id:
            return r
    raise KeyError(f"region {region_id!r} not in ground truth")


# ---------------------------------------------------------------------------
# Candidate markdown, built from the committed ground truth (never hardcoded
# independently of it, so a fixture edit cannot silently desync the tests).
# ---------------------------------------------------------------------------


def _md(columns: list[str], rows: list[dict], row_label_order: list[str] | None = None) -> str:
    """Render a markdown table. ``row_label_order`` overrides which LABEL is
    printed for each positional row while keeping that row's own values --
    the shape a row-label-shift defect actually takes (values untouched,
    labels permuted)."""
    labels = row_label_order or [r["label"] for r in rows]
    header = "| Label | " + " | ".join(columns) + " |"
    sep = "| --- | " + " | ".join("---" for _ in columns) + " |"
    lines = [header, sep]
    for row, label in zip(rows, labels):
        lines.append(f"| {label} | " + " | ".join(row[c] for c in columns) + " |")
    return "\n".join(lines) + "\n"


_GT = _load_gt()
_CLEAN_REGION = _region(_GT, "clean_table")
_SHIFT_REGION = _region(_GT, "shift_table")

_CLEAN_ROWS = [
    {"label": lbl, "Value": _CLEAN_REGION["cells"][f"{lbl}|Value"]}
    for lbl in _CLEAN_REGION["row_labels"]
]
_SHIFT_ROWS = [
    {
        "label": lbl,
        "OLS": _SHIFT_REGION["cells"][f"{lbl}|OLS"],
        "IV": _SHIFT_REGION["cells"][f"{lbl}|IV"],
    }
    for lbl in _SHIFT_REGION["row_labels"]
]

CLEAN_MD = _md(_CLEAN_REGION["columns"], _CLEAN_ROWS)
SHIFT_CORRECT_MD = _md(_SHIFT_REGION["columns"], _SHIFT_ROWS)
SHIFT_SHIFTED_MD = _md(
    _SHIFT_REGION["columns"], _SHIFT_ROWS, row_label_order=_SHIFT_REGION["shifted_row_label_order"]
)

CLEAN_PAGE = _CLEAN_REGION["page"]
SHIFT_PAGE = _SHIFT_REGION["page"]


# ---------------------------------------------------------------------------
# Scripted rungs: decide verdict from the exact candidate markdown handed to
# them, so a single fake object serves every witnessed table across the
# whole document without ever running out of queued results.
# ---------------------------------------------------------------------------


def _pass_verdict(confidence: str = "high") -> TableJudgeVerdict:
    return TableJudgeVerdict(verdict="PASS", confidence=confidence, findings=[])


def _fail_verdict() -> TableJudgeVerdict:
    return TableJudgeVerdict(
        verdict="FAIL",
        confidence="high",
        findings=[Finding(code=FindingCode.WRONG_BINDING, where="row", detail="judge rejects")],
    )


class _ScriptedRung:
    """A ``RungCallable`` keyed by the exact candidate markdown text it is
    handed. Records every call for assertion (which table was actually
    judged, and with what ``prior_findings``)."""

    def __init__(self, verdicts: dict[str, RungResult], rung_id: str = "fake1") -> None:
        self._verdicts = verdicts
        self.rung_id = rung_id
        self.calls: list[tuple] = []

    def __call__(self, crop_path, markdown, prior_findings):
        self.calls.append((crop_path, markdown, prior_findings))
        key = markdown.strip()
        if key not in self._verdicts:
            raise AssertionError(f"unscripted markdown judged by {self.rung_id}: {key!r}")
        return self._verdicts[key]


# ---------------------------------------------------------------------------
# Pipeline / process() helpers
# ---------------------------------------------------------------------------


def _make_config(
    table_judge_ladder: bool = False,
    **overrides,
) -> PipelineConfig:
    kwargs = dict(
        primary_engine=EngineType.QWEN,
        agentic=True,
        judge_backend="heuristic",
        enabled_engines=[EngineType.QWEN],
        quiet=True,
        save_figures=False,
        write_manifest=False,
    )
    kwargs.update(overrides)
    return PipelineConfig(
        table_judge_ladder=table_judge_ladder,  # docs/log/2026-09-03_p1-prep-latch-and-audit.md
        **kwargs,
    )


def _route_page_per_page(text_by_page: dict[int, str]):
    def _fake_route(page_num, ladder, run_provider, judge, **kwargs):
        from socr.pipeline.agentic import PageDecision, ProviderAttempt

        text = text_by_page[page_num]
        out = PageOutput(
            page_num=page_num,
            text=text,
            status=PageStatus.SUCCESS,
            engine="qwen",
            audit_passed=True,
        )
        prof = ladder[0]
        att = ProviderAttempt(
            engine=prof.engine,
            output=out,
            cost_usd=prof.cost_per_page_usd,
            accepted=True,
            reason="ok",
            provider_id=prof.id,
            model=prof.model,
            backend=prof.backend,
        )
        return PageDecision(page_num=page_num, final_output=out, attempts=[att], accepted=True)

    return _fake_route


def _process_and_capture(
    pipeline: UnifiedPipeline, pdf_path: Path, out_dir: Path
) -> tuple[object, object]:
    """Run ``process()`` and also return the ``DocumentState`` it built, by
    spying on ``_phase_assemble`` (the only seam holding a reference to it) --
    so the CLI summary surface (``_print_summary``, which takes ``state``)
    can be exercised against the SAME run the document/metadata assertions
    check, without process() itself needing to expose ``state``."""
    captured: dict[str, object] = {}
    original = pipeline._phase_assemble

    def _spy(state, out_dir_):
        captured["state"] = state
        return original(state, out_dir_)

    with patch.object(pipeline, "_phase_assemble", side_effect=_spy):
        result = pipeline.process(pdf_path, out_dir)
    return result, captured["state"]


def _run(
    pdf_path: Path,
    out_dir: Path,
    *,
    ladder_on: bool,
    text_by_page: dict[int, str],
    rungs: list | None,
):
    cfg = _make_config(table_judge_ladder=ladder_on)
    pipeline = UnifiedPipeline(cfg)
    patches = [
        patch(
            "socr.pipeline.orchestrator.route_page",
            side_effect=_route_page_per_page(text_by_page),
        ),
        patch.object(pipeline, "_available_engines_for_agentic", return_value=[PROFILE_QWEN_LOCAL]),
        patch.object(pipeline, "_resolve_judge_model", return_value=""),
    ]
    if ladder_on:
        patches.append(patch.object(pipeline, "_build_table_judge_rungs", return_value=rungs or []))
    with contextlib.ExitStack() as stack:
        for p in patches:
            stack.enter_context(p)
        result, state = _process_and_capture(pipeline, pdf_path, out_dir)
    return pipeline, result, state


def _metadata(out_dir: Path, pdf_path: Path) -> dict:
    doc_dir = out_dir / pdf_path.stem
    return json.loads((doc_dir / "metadata.json").read_text(encoding="utf-8"))


def _fixture_copy(tmp_path: Path, name: str) -> Path:
    dest = tmp_path / name
    dest.mkdir(parents=True, exist_ok=True)
    pdf_path = dest / "binding_shift_doc.pdf"
    shutil.copyfile(FIXTURE_PDF, pdf_path)
    return pdf_path


# ---------------------------------------------------------------------------
# Fixture sanity (pass now, no xfail)
# ---------------------------------------------------------------------------


class TestFixtureSanity:
    def test_pdf_and_ground_truth_exist(self) -> None:
        assert FIXTURE_PDF.exists()
        assert GROUND_TRUTH.exists()

    def test_two_pages_born_digital(self) -> None:
        doc = fitz.open(str(FIXTURE_PDF))
        assert doc.page_count == 2
        for i in range(2):
            assert len(doc[i].get_text("words")) >= 6
        doc.close()

    def test_ground_truth_two_table_regions(self) -> None:
        gt = _load_gt()
        assert [r["id"] for r in gt["regions"]] == ["clean_table", "shift_table"]

    def test_shifted_row_label_order_is_a_permutation_not_identity(self) -> None:
        region = _region(_load_gt(), "shift_table")
        shifted = region["shifted_row_label_order"]
        assert sorted(shifted) == sorted(region["row_labels"])
        assert shifted != region["row_labels"]

    def test_shifted_markdown_preserves_the_value_multiset(self) -> None:
        """The GH-273 shape itself: SHIFT_SHIFTED_MD carries the exact same
        multiset of values as SHIFT_CORRECT_MD -- only row/label binding
        differs, so a value-presence-only check cannot tell them apart."""
        import re

        def _values(md: str) -> list[str]:
            vals = []
            for line in md.splitlines()[2:]:
                cells = [c.strip() for c in line.strip("|").split("|")]
                vals.extend(cells[1:])
            return sorted(vals)

        assert _values(SHIFT_SHIFTED_MD) == _values(SHIFT_CORRECT_MD)
        assert SHIFT_SHIFTED_MD != SHIFT_CORRECT_MD


# ---------------------------------------------------------------------------
# Terminal sweeps: flag off (baseline) vs flag on, asserting the DELTA at
# all four no-silent-loss surfaces.
# ---------------------------------------------------------------------------


class TestRejectedTerminal:
    """Real judge FAIL on the shifted table -> TABLE_REJECTED, not retryable."""

    def test_flag_off_vs_on(self, tmp_path: Path, capsys) -> None:
        text_by_page = {CLEAN_PAGE: CLEAN_MD, SHIFT_PAGE: SHIFT_SHIFTED_MD}

        # -- flag off: baseline, both tables ship unchecked -----------------
        pdf_off = _fixture_copy(tmp_path, "off")
        _pipe_off, result_off, state_off = _run(
            pdf_off, tmp_path / "off_out", ladder_on=False, text_by_page=text_by_page, rungs=None
        )
        assert result_off.status == DocumentStatus.SUCCESS
        assert state_off.pages[CLEAN_PAGE].table_ladder_disposition is None
        assert state_off.pages[SHIFT_PAGE].table_ladder_disposition is None
        meta_off = _metadata(tmp_path / "off_out", pdf_off)
        assert meta_off["status"] != "partial"
        assert "table_rejected" not in json.dumps(meta_off)

        # -- flag on: shifted table rejected by the (real) judge ------------
        rung = _ScriptedRung(
            {
                CLEAN_MD.strip(): RungResult(rung="fake1", ok=True, verdict=_pass_verdict("high")),
                SHIFT_SHIFTED_MD.strip(): RungResult(
                    rung="fake1", ok=True, verdict=_fail_verdict()
                ),
            }
        )
        pdf_on = _fixture_copy(tmp_path, "on")
        _pipe_on, result_on, state_on = _run(
            pdf_on,
            tmp_path / "on_out",
            ladder_on=True,
            text_by_page=text_by_page,
            rungs=[rung],
        )

        # Page disposition: the demotion is per-page, not document-wide.
        # GH-575 (cold review round 1, finding 1): this fixture is a genuine
        # row-label shift, so native geometry ACTIVELY contradicts the emitted
        # grid -- and an active contradiction is terminal, ending the table
        # UNVERIFIED without asking the blind adjudicator. Withholding requires
        # a blind reader to have looked and disagreed, which cannot happen
        # here. Every surface below moves with the label; the
        # per-page-not-document-wide property this test exists for is
        # unchanged, and so is the flag-off/flag-on difference.
        assert state_on.pages[SHIFT_PAGE].table_ladder_disposition == FailureMode.TABLE_UNVERIFIED
        assert state_on.pages[CLEAN_PAGE].table_ladder_disposition is None

        # Document status.
        assert result_on.status == DocumentStatus.AUDIT_FAILED
        assert "table_unverified" in (result_on.error or "")
        assert str(SHIFT_PAGE) in (result_on.error or "")

        # metadata.json note.
        meta_on = _metadata(tmp_path / "on_out", pdf_on)
        assert meta_on["status"] == "partial"
        assert "table_unverified" in meta_on["error"]
        assert str(SHIFT_PAGE) in meta_on["error"]

        # CLI summary.
        _pipe_on._print_summary(result_on, state_on)
        captured = capsys.readouterr()
        assert "table_unverified" in captured.out


class TestPlainUnverifiedTerminal:
    """An infra (¬S1) rung on the CLEAN table -> TABLE_UNVERIFIED, retryable,
    with NO mechanical evidence involved -- the plain infra shape."""

    def test_flag_off_vs_on(self, tmp_path: Path, capsys) -> None:
        text_by_page = {CLEAN_PAGE: CLEAN_MD, SHIFT_PAGE: SHIFT_CORRECT_MD}

        pdf_off = _fixture_copy(tmp_path, "off")
        _pipe_off, result_off, state_off = _run(
            pdf_off, tmp_path / "off_out", ladder_on=False, text_by_page=text_by_page, rungs=None
        )
        assert result_off.status == DocumentStatus.SUCCESS
        meta_off = _metadata(tmp_path / "off_out", pdf_off)
        assert "table_unverified" not in json.dumps(meta_off)

        rung = _ScriptedRung(
            {
                SHIFT_CORRECT_MD.strip(): RungResult(
                    rung="fake1", ok=True, verdict=_pass_verdict("high")
                ),
                CLEAN_MD.strip(): RungResult(
                    rung="fake1", ok=False, error="simulated infra failure"
                ),
            }
        )
        pdf_on = _fixture_copy(tmp_path, "on")
        _pipe_on, result_on, state_on = _run(
            pdf_on,
            tmp_path / "on_out",
            ladder_on=True,
            text_by_page=text_by_page,
            rungs=[rung],
        )

        assert state_on.pages[CLEAN_PAGE].table_ladder_disposition == FailureMode.TABLE_UNVERIFIED
        assert state_on.pages[SHIFT_PAGE].table_ladder_disposition is None

        assert result_on.status == DocumentStatus.AUDIT_FAILED
        assert "table_unverified" in (result_on.error or "")
        assert str(CLEAN_PAGE) in (result_on.error or "")

        meta_on = _metadata(tmp_path / "on_out", pdf_on)
        assert meta_on["status"] == "partial"
        assert "table_unverified" in meta_on["error"]

        _pipe_on._print_summary(result_on, state_on)
        captured = capsys.readouterr()
        assert "table_unverified" in captured.out

        # Distinguish from the CLAMPED case below: no mechanical wording.
        unverified_events = [e for e in state_on.events if e.kind == TABLE_LADDER_UNVERIFIED_KIND]
        assert unverified_events
        assert all("mechanical binding check" not in e.detail for e in unverified_events)


class TestClampedUnverifiedTerminal:
    """Mechanical contradiction on the shifted table + a high-confidence real
    PASS -> CONSILIUM's clamp caps the table at UNVERIFIED (never silently
    ACCEPTED, never REJECTED by the clamp alone) -- distinct from plain
    infra UNVERIFIED by both its trigger (S1 held; the judge DID answer) and
    its audit-event wording."""

    def test_flag_off_vs_on(self, tmp_path: Path, capsys) -> None:
        text_by_page = {CLEAN_PAGE: CLEAN_MD, SHIFT_PAGE: SHIFT_SHIFTED_MD}

        pdf_off = _fixture_copy(tmp_path, "off")
        _pipe_off, result_off, state_off = _run(
            pdf_off, tmp_path / "off_out", ladder_on=False, text_by_page=text_by_page, rungs=None
        )
        assert result_off.status == DocumentStatus.SUCCESS
        meta_off = _metadata(tmp_path / "off_out", pdf_off)
        assert "table_unverified" not in json.dumps(meta_off)

        # Both tables get a high-confidence real PASS -- the ladder alone
        # would ACCEPT both; only the mechanical clamp demotes the shifted one.
        rung = _ScriptedRung(
            {
                CLEAN_MD.strip(): RungResult(rung="fake1", ok=True, verdict=_pass_verdict("high")),
                SHIFT_SHIFTED_MD.strip(): RungResult(
                    rung="fake1", ok=True, verdict=_pass_verdict("high")
                ),
            }
        )
        pdf_on = _fixture_copy(tmp_path, "on")
        _pipe_on, result_on, state_on = _run(
            pdf_on,
            tmp_path / "on_out",
            ladder_on=True,
            text_by_page=text_by_page,
            rungs=[rung],
        )

        # GH-359 ruling 4: the real rung does NOT see mechanical findings
        # (crop + markdown, nothing else). Ruling 5: the clamp still fires.
        shift_calls = [c for c in rung.calls if c[1].strip() == SHIFT_SHIFTED_MD.strip()]
        assert shift_calls
        assert shift_calls[0][2] is None

        assert state_on.pages[SHIFT_PAGE].table_ladder_disposition == FailureMode.TABLE_UNVERIFIED
        assert state_on.pages[CLEAN_PAGE].table_ladder_disposition is None

        assert result_on.status == DocumentStatus.AUDIT_FAILED
        assert "table_unverified" in (result_on.error or "")
        assert str(SHIFT_PAGE) in (result_on.error or "")

        meta_on = _metadata(tmp_path / "on_out", pdf_on)
        assert meta_on["status"] == "partial"
        assert "table_unverified" in meta_on["error"]

        _pipe_on._print_summary(result_on, state_on)
        captured = capsys.readouterr()
        assert "table_unverified" in captured.out

        # The distinguishing wording from plain infra UNVERIFIED.
        unverified_events = [e for e in state_on.events if e.kind == TABLE_LADDER_UNVERIFIED_KIND]
        assert unverified_events
        assert any(
            "mechanical binding check found a contradiction" in e.detail for e in unverified_events
        )
