"""GH-214: a code fix must not be silently skipped on already-terminal pages.

``_run_fingerprint`` records the run *configuration*. It never recorded socr's own
code, so fixing an extraction bug without touching config produced a byte-identical
fingerprint, the per-page resume gate skipped every finished page, and the document
reported SUCCESS still carrying the output the fix was meant to replace.

These tests are hermetic: no engine, no provider, no ollama. The source-change case is
simulated by monkeypatching the digest helper rather than mutating files on disk, so
the test is fast and cannot corrupt the checkout it runs in.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from socr.core.config import PipelineConfig
from socr.pipeline import orchestrator as orch


@pytest.fixture(autouse=True)
def _clear_digest_cache():
    """The digest is cached per process; tests must not inherit each other's value."""
    orch._SOURCE_DIGEST_CACHE = None
    yield
    orch._SOURCE_DIGEST_CACHE = None


def _pipeline():
    return orch.UnifiedPipeline(PipelineConfig())


def test_source_digest_is_in_the_run_fingerprint(monkeypatch: pytest.MonkeyPatch) -> None:
    """Identical config plus different socr source must yield different fingerprints.

    This is the whole ticket. If the ``socr_source_digest`` line is removed from
    ``_run_fingerprint``'s extra dict, both calls return the same value and this fails.
    """
    pipeline = _pipeline()

    monkeypatch.setattr(orch, "_socr_source_digest", lambda: "digest-before-the-fix")
    before = pipeline._run_fingerprint()

    monkeypatch.setattr(orch, "_socr_source_digest", lambda: "digest-after-the-fix")
    after = pipeline._run_fingerprint()

    assert before != after, "a source change must invalidate the run fingerprint"


def test_same_source_yields_a_stable_fingerprint(monkeypatch: pytest.MonkeyPatch) -> None:
    """The converse: unchanged code must NOT invalidate, or resume is worthless."""
    pipeline = _pipeline()
    monkeypatch.setattr(orch, "_socr_source_digest", lambda: "steady-digest")

    assert pipeline._run_fingerprint() == pipeline._run_fingerprint()


def test_digest_is_deterministic_and_content_sensitive(tmp_path: Path) -> None:
    """Two checkouts of identical code agree; a one-byte change does not.

    Paths are recorded package-relative, so the absolute location must not leak into
    the hash -- otherwise every machine would disagree and nothing would ever resume.
    """
    import hashlib

    def digest_of(root: Path) -> str:
        h = hashlib.sha256()
        for path in sorted(root.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            h.update(str(path.relative_to(root)).encode())
            h.update(b"\x00")
            h.update(path.read_bytes())
            h.update(b"\x00")
        return h.hexdigest()

    a = tmp_path / "checkout_a"
    b = tmp_path / "checkout_b"
    for root in (a, b):
        (root / "pkg").mkdir(parents=True)
        (root / "pkg" / "mod.py").write_text("VALUE = 1\n")

    assert digest_of(a) == digest_of(b), "absolute path leaked into the digest"

    (b / "pkg" / "mod.py").write_text("VALUE = 2\n")
    assert digest_of(a) != digest_of(b), "a content change must change the digest"


def test_digest_ignores_pycache(tmp_path: Path) -> None:
    """Generated bytecode must not perturb the digest; only source counts."""
    import hashlib

    def digest_of(root: Path) -> str:
        h = hashlib.sha256()
        for path in sorted(root.rglob("*.py")):
            if "__pycache__" in path.parts:
                continue
            h.update(str(path.relative_to(root)).encode())
            h.update(b"\x00")
            h.update(path.read_bytes())
            h.update(b"\x00")
        return h.hexdigest()

    root = tmp_path / "pkg"
    root.mkdir()
    (root / "mod.py").write_text("VALUE = 1\n")
    before = digest_of(root)

    cache = root / "__pycache__"
    cache.mkdir()
    (cache / "mod.cpython-311.py").write_text("garbage\n")

    assert digest_of(root) == before


def test_real_digest_is_a_nonempty_hex_string() -> None:
    """Guard the sentinel path: a readable tree must produce a real digest."""
    value = orch._socr_source_digest()

    assert value != "unreadable-source-tree"
    assert len(value) == 64
    assert int(value, 16) >= 0


def test_digest_is_cached_per_process(monkeypatch: pytest.MonkeyPatch) -> None:
    """Hashing the tree once per page would be a real cost on a 68-page document."""
    orch._SOURCE_DIGEST_CACHE = None
    calls = {"n": 0}
    real_sha = __import__("hashlib").sha256

    def counting_sha256(*args, **kwargs):
        calls["n"] += 1
        return real_sha(*args, **kwargs)

    monkeypatch.setattr("hashlib.sha256", counting_sha256)
    orch._socr_source_digest()
    after_first = calls["n"]
    orch._socr_source_digest()

    assert calls["n"] == after_first, "digest recomputed instead of served from cache"


def test_sidecar_records_which_socr_produced_the_page(tmp_path: Path) -> None:
    """Provenance must be answerable for a page already on disk.

    The fingerprint prevents stale REUSE going forward, but it is an opaque hash: it
    cannot tell you whether a page sitting in an existing corpus predates a fix.
    """
    sidecar = json.loads(
        json.dumps(
            {
                "socr_version": orch._socr_version(),
                "socr_source_digest": orch._socr_source_digest(),
            }
        )
    )

    assert sidecar["socr_version"], "version must be recorded, not blank"
    assert len(sidecar["socr_source_digest"]) == 64


def test_missing_provenance_in_an_old_sidecar_cannot_match(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    """Existing corpora have no digest at all; they must reprocess, never grandfather.

    An old sidecar's fingerprint was computed without the digest key, so it cannot
    equal a new one. Treating "no recorded code identity" as "close enough" would
    reopen exactly this bug.
    """
    pipeline = _pipeline()
    monkeypatch.setattr(orch, "_socr_source_digest", lambda: "current-code")
    current = pipeline._run_fingerprint()

    legacy_sidecar = {"terminal": True, "run_fingerprint": "fp:written-before-gh214"}

    assert legacy_sidecar["run_fingerprint"] != current
